name: product_ordering_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  keyboard_dismisser:
  responsive_sizer:
  geolocator: 
  geocoding:
  google_fonts:
  flutter_native_splash: ^2.2.4
  flutter_otp_text_field:
  dotted_line:
  flutter_map:
  latlong2:
  animated_custom_dropdown:
  font_awesome_flutter:
  image_picker:
  carousel_slider:
flutter_native_splash:
  background_image: assets/images/splashScreenBg.png # Path to your splash screen image
  android: true # Generate splash screen for Android
  ios: true # Generate splash screen for iOS
  web: true # Generate splash screen for Web (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/img/

